# Generated by Django 4.2.30 on 2026-07-03 07:54

import classes.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LiveClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_id', models.CharField(default=classes.models.generate_class_id, max_length=12, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('password', models.CharField(default=classes.models.generate_password, max_length=10)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('live', 'Live'), ('ended', 'Ended')], default='scheduled', max_length=20)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stream_key', models.CharField(blank=True, max_length=64, unique=True)),
                ('chat_enabled', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('session_key', models.CharField(blank=True, max_length=64)),
                ('live_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='classes.liveclass')),
            ],
            options={
                'ordering': ['-joined_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_name', models.CharField(max_length=100)),
                ('is_admin', models.BooleanField(default=False)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('live_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='classes.liveclass')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
